### ISSUE TITLE
Pytearcat Package can't be installed

### ISSUE THREAD

**Issue by Mreality69** [pytearcat/pytearcat#11] opened 2023-06-17 08:26 UTC
While I am trying the install the pytearcat , It does not work. A massage shown in the output that "Failed building wheel for numpy...". I've tried in both jupyter notebooks and local computer. But it didn't even work in one of them. How can I fix that?

**Comment by jmsureda** [comment] 2023-06-23 09:27
Hi [Mreality69](https://github.com/Mreality69),

Thanks for reporting this! 

I checked recently and I am aware of the issue. It is produced due to a dependence on a specific version of `NumPy`. I will try to fix it as soon as I can and will update the PyPi version of `Pytearcat` to solve the problem.

**Comment by jmsureda** [comment] 2023-07-21 22:05
This issue was solved in the release [0.0.6](https://github.com/pytearcat/pytearcat/releases/tag/0.0.6), already on PyPI.

**Comment by Mreality69** [comment] 2023-07-22 03:51
That's great. Thanks a lot. I will try out it very soon.

**Comment by jmsureda** [comment] 2023-08-11 10:44
Closing this now as it should be working as intended.

**Closed by jmsureda** 2023-08-11 10:44 UTC
Labels: bug
